prometheus:
  url: http://prometheus-server.default.svc
  port: 80

rules:
  default: false
  custom:
  - seriesQuery: 'http_requests_total{service="podinfo-service"}'
    resources:
      template: <<.Resource>>
    name:
      matches: "http_requests_total"
      as: "http_requests_per_second"
    metricsQuery: "sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)"
