prometheus:
  url: http://prometheus-server.default.svc
  port: 80


rules:
  default: false
  custom:
    - seriesQuery: 'http_requests_total{app="podinfo"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "http_requests_total"
        as: "http_requests_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'